/* EasyTier Config Server - Device Connection Manager */

#ifndef EASYTIER_CONFIG_SERVER_H
#define EASYTIER_CONFIG_SERVER_H

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 创建 NetworkConfigService 单例
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool create_network_config_service_singleton(const char *DB_URL,
                                             const char *GEOIP_PATH,
                                             char **ERR_MSG);

/**
 * 启动 NetworkConfigService 的监听器
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_singleton_start(const char *PROTOCOL, uint16_t PORT, char **ERR_MSG);

/**
 * 销毁 NetworkConfigService 实例并释放资源
 *
 * # Safety
 *
 * 这个函数是不安全的
 */
bool destroy_network_config_service_singleton(char **ERR_MSG);

/**
 * 释放由 C 字符串指针占用的内存
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
void free_c_char(char *S);

/**
 * 收集单个网络实例信息
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_collect_one_network_info(const char *ORG_ID,
                                                     const char *DEVICE_ID,
                                                     const char *INST_ID,
                                                     char **RESULT_JSON_OUT,
                                                     char **ERR_MSG);

/**
 * 收集多个网络实例信息
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_collect_network_info(const char *ORG_ID,
                                                 const char *DEVICE_ID,
                                                 const char *INST_IDS_JSON,
                                                 char **RESULT_JSON_OUT,
                                                 char **ERR_MSG);

/**
 * 列出网络实例 ID
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_list_network_instance_ids(const char *ORG_ID,
                                                      const char *DEVICE_ID,
                                                      char **RESULT_JSON_OUT,
                                                      char **ERR_MSG);

/**
 * 删除网络实例
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_remove_network_instance(const char *ORG_ID,
                                                    const char *DEVICE_ID,
                                                    const char *INST_ID,
                                                    char **ERR_MSG);

/**
 * 列出设备
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_list_devices(const char *ORG_ID,
                                         char **RESULT_JSON_OUT,
                                         char **ERR_MSG);

/**
 * 更新网络状态
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_update_network_state(const char *ORG_ID,
                                                 const char *DEVICE_ID,
                                                 const char *INST_ID,
                                                 bool DISABLED,
                                                 char **ERR_MSG);

/**
 * 验证网络配置
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_validate_config(const char *ORG_ID,
                                            const char *DEVICE_ID,
                                            const char *CONFIG_JSON,
                                            char **ERR_MSG);

/**
 * 运行网络实例
 *
 * # Safety
 *
 * 这个函数是不安全的，因为它接受原始指针作为参数
 */
bool network_config_service_run_network_instance(const char *ORG_ID,
                                                 const char *DEVICE_ID,
                                                 const char *CONFIG_JSON,
                                                 char **INST_ID_OUT,
                                                 char **ERR_MSG);

#endif  /* EASYTIER_CONFIG_SERVER_H */
