/* EasyTier Common - Shared Utilities */

#ifndef EASYTIER_COMMON_H
#define EASYTIER_COMMON_H

/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Get last error message
 */
const char *easytier_common_get_error_msg(void);

/**
 * Free a C string allocated by Rust
 */
void easytier_common_free_string(const char *S);

/**
 * Free an array of C strings
 *
 * # Safety
 *
 * The caller must ensure that `arr` was allocated by Rust and contains `count` valid C string pointers.
 */
void easytier_common_free_string_array(const char *const *ARR,
                                       int32_t COUNT);

/**
 * FFI wrapper: Initialize console logging
 *
 * # Safety
 *
 * The caller must ensure that `level` and `module_name` are valid C strings.
 */
int easytier_common_init_console_logging(const char *LEVEL, const char *MODULE_NAME);

/**
 * FFI wrapper: Initialize file logging
 *
 * # Safety
 *
 * The caller must ensure that `level`, `module_name`, and `log_path` are valid C strings.
 */
int easytier_common_init_file_logging(const char *LEVEL,
                                      const char *MODULE_NAME,
                                      const char *LOG_PATH);

#endif  /* EASYTIER_COMMON_H */
