name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # Fast jobs that don't need database
  quick-checks:
    name: Quick Checks (Format, Clippy, Build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-set: ["server", "client", "default"]
    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          target/debug/deps
          target/debug/build
          target/debug/.fingerprint
        key: ${{ runner.os }}-quick-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-quick-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-quick-${{ matrix.feature-set }}-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler

    - name: Check formatting
      if: matrix.feature-set == 'default'
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo clippy --all-targets --all-features -- -D warnings
        else
          cargo clippy --no-default-features --features ${{ matrix.feature-set }} -- -D warnings
        fi

    - name: Build check
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo check --all-targets --all-features
        elif [ "${{ matrix.feature-set }}" = "server" ]; then
          cargo check --no-default-features --features server --all-targets
        elif [ "${{ matrix.feature-set }}" = "client" ]; then
          # Client-only build: only check lib, skip integration tests that require server modules
          cargo check --no-default-features --features client --lib
        fi

  # Fast unit tests without database
  unit-tests:
    name: Unit Tests (No Database)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-set: ["server", "client", "default"]
    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          target/debug/deps
          target/debug/build
          target/debug/.fingerprint
        key: ${{ runner.os }}-test-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-test-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-test-${{ matrix.feature-set }}-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler

    - name: Run unit tests
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo test --lib --verbose
        elif [ "${{ matrix.feature-set }}" = "server" ]; then
          cargo test --no-default-features --features server --lib --verbose
        elif [ "${{ matrix.feature-set }}" = "client" ]; then
          # Client-only tests: only run lib tests, skip integration tests that require server modules
          cargo test --no-default-features --features client --lib --verbose
        fi

  # Integration tests with database (only for server feature)
  integration-tests:
    name: Integration Tests (With Database)
    runs-on: ubuntu-latest
    needs: [quick-checks, unit-tests]  # Wait for fast jobs first
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: easytier_bridge_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        # Remove unnecessary tools and files
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        echo "Disk space after cleanup:"
        df -h

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry and git
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache build artifacts
      uses: actions/cache@v4
      with:
        path: |
          target/debug/deps
          target/debug/build
          target/debug/.fingerprint
        key: ${{ runner.os }}-integration-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-integration-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-integration-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler

    - name: Run server integration tests
      run: cargo test --no-default-features --features server --verbose
      env:
        DATABASE_URL: mysql://root:root123@127.0.0.1:3306/easytier_bridge_test

    - name: Clean build artifacts to save space
      run: |
        cargo clean --release
        rm -rf target/debug/incremental
        echo "Disk space after cleaning:"
        df -h

    - name: Run full integration tests
      run: cargo test --all-features --verbose
      env:
        DATABASE_URL: mysql://root:root123@127.0.0.1:3306/easytier_bridge_test

  # C header generation (only run once)
  c-headers:
    name: Generate C Headers
    runs-on: ubuntu-latest
    needs: quick-checks  # Wait for format/clippy checks
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/debug/deps
          target/debug/build
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler
        cargo install cbindgen --force

    - name: Generate C headers
      run: |
        mkdir -p include
        cbindgen --config cbindgen.toml --crate easytier-bridge --output include/easytier_bridge.h

    - name: Verify C headers
      run: |
        if [ ! -f include/easytier_bridge.h ]; then
          echo "Error: C header file not generated"
          exit 1
        fi
        echo "C header file size: $(wc -c < include/easytier_bridge.h) bytes"

  # Coverage (only run on main branch to save resources)
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    needs: [quick-checks, unit-tests]  # Don't wait for slow integration tests
    timeout-minutes: 60  # Realistic timeout for coverage builds
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: easytier_bridge_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Cache cargo registry and git
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache coverage build artifacts
      uses: actions/cache@v4
      with:
        path: |
          target/llvm-cov-target
          target/debug/deps
          target/debug/build
          target/debug/.fingerprint
        key: ${{ runner.os }}-coverage-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-coverage-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-coverage-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate code coverage (lib only for speed)
      env:
        DATABASE_URL: mysql://root:root123@127.0.0.1:3306/easytier_bridge_test
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-C instrument-coverage"
      run: |
        echo "Running coverage on library code only to reduce compilation time..."
        cargo llvm-cov --lib --all-features --lcov --output-path lcov.info
      timeout-minutes: 45

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true

  # Final status check
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [quick-checks, unit-tests, integration-tests, c-headers]
    if: always()
    steps:
    - name: Check all jobs
      run: |
        if [ "${{ needs.quick-checks.result }}" != "success" ] || \
           [ "${{ needs.unit-tests.result }}" != "success" ] || \
           [ "${{ needs.integration-tests.result }}" != "success" ] || \
           [ "${{ needs.c-headers.result }}" != "success" ]; then
          echo "One or more CI jobs failed"
          exit 1
        fi
        echo "All CI jobs passed successfully!"