name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0  # Disable incremental compilation for better caching
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  # Fast jobs that don't need database
  quick-checks:
    name: Quick Checks (Format, Clippy, Build)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        feature-set: ["server", "client", "default"]
    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc &

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache cargo and build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.feature-set }}-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler clang mold

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Configure build environment
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
        echo "linker = \"clang\"" >> ~/.cargo/config.toml
        echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=/usr/bin/mold\"]" >> ~/.cargo/config.toml

    - name: Check formatting
      if: matrix.feature-set == 'default'
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo clippy --all-targets --all-features -- -D warnings
        else
          cargo clippy --no-default-features --features ${{ matrix.feature-set }} -- -D warnings
        fi

    - name: Build check
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo check --all-targets --all-features
        elif [ "${{ matrix.feature-set }}" = "server" ]; then
          cargo check --no-default-features --features server --all-targets
        elif [ "${{ matrix.feature-set }}" = "client" ]; then
          # Client-only build: only check lib, skip integration tests that require server modules
          cargo check --no-default-features --features client --lib
        fi

  # Fast unit tests without database
  unit-tests:
    name: Unit Tests (No Database)
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        feature-set: ["server", "client", "default"]
    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc &

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo and build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.feature-set }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.feature-set }}-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler clang mold

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Configure build environment
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
        echo "linker = \"clang\"" >> ~/.cargo/config.toml
        echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=/usr/bin/mold\"]" >> ~/.cargo/config.toml

    - name: Run unit tests
      run: |
        if [ "${{ matrix.feature-set }}" = "default" ]; then
          cargo test --lib
        elif [ "${{ matrix.feature-set }}" = "server" ]; then
          cargo test --no-default-features --features server --lib
        elif [ "${{ matrix.feature-set }}" = "client" ]; then
          # Client-only tests: only run lib tests, skip integration tests that require server modules
          cargo test --no-default-features --features client --lib
        fi

  # Integration tests with database (only for server feature)
  integration-tests:
    name: Integration Tests (With Database)
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: [quick-checks, unit-tests]  # Wait for fast jobs first
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: easytier_bridge_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        # Remove unnecessary tools and files
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        echo "Disk space after cleanup:"
        df -h

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo and build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-integration-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-integration-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler clang mold

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4
        
    - name: Configure build environment
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
        echo "linker = \"clang\"" >> ~/.cargo/config.toml
        echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=/usr/bin/mold\"]" >> ~/.cargo/config.toml
        cat ~/.cargo/config.toml

    - name: Run integration tests
      run: cargo test --all-features -- --test-threads=2
      env:
        DATABASE_URL: mysql://root:root123@127.0.0.1:3306/easytier_bridge_test

  # C header generation (only run once)
  c-headers:
    name: Generate C Headers
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: quick-checks  # Wait for format/clippy checks
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo and build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-headers-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-headers-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler

    - name: Install cbindgen
      run: |
        # Try to use cached version first
        if ! command -v cbindgen &> /dev/null; then
          cargo install cbindgen --locked
        fi

    - name: Generate C headers
      run: |
        mkdir -p include
        cbindgen --config cbindgen.toml --crate easytier-bridge --output include/easytier_bridge.h

    - name: Verify C headers
      run: |
        if [ ! -f include/easytier_bridge.h ]; then
          echo "Error: C header file not generated"
          exit 1
        fi
        echo "C header file size: $(wc -c < include/easytier_bridge.h) bytes"

  # Coverage (only run on main and develop branches to save resources)
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs: [quick-checks, unit-tests]  # Don't wait for slow integration tests
    timeout-minutes: 60  # Realistic timeout for coverage builds
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: easytier_bridge_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Cache cargo and build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-coverage-
          ${{ runner.os }}-cargo-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libssl-dev protobuf-compiler clang mold

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.4

    - name: Configure build environment
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "[target.x86_64-unknown-linux-gnu]" > ~/.cargo/config.toml
        echo "linker = \"clang\"" >> ~/.cargo/config.toml
        echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=/usr/bin/mold\"]" >> ~/.cargo/config.toml

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate code coverage
      env:
        DATABASE_URL: mysql://root:root123@127.0.0.1:3306/easytier_bridge_test
      run: |
        echo "Running coverage on library code only to reduce compilation time..."
        cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info --lib
      timeout-minutes: 45

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true

  # Final status check
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [quick-checks, unit-tests, integration-tests, c-headers]
    if: always()
    steps:
    - name: Check all jobs
      run: |
        if [ "${{ needs.quick-checks.result }}" != "success" ] || \
           [ "${{ needs.unit-tests.result }}" != "success" ] || \
           [ "${{ needs.integration-tests.result }}" != "success" ] || \
           [ "${{ needs.c-headers.result }}" != "success" ]; then
          echo "One or more CI jobs failed"
          exit 1
        fi
        echo "All CI jobs passed successfully!"